name: about me
on: push
jobs:
    me:
        runs-on: ubuntu-latest
        steps:
            - name: print pwd
              run: pwd
            - name: print whoami
              run: whoami
            - name: print date
              run: date
            