name: about me
on: push
jobs:
    me:
        runs-on: ubuntu-latest
        steps:
            - name: print pwd
              run: echo $pwd
            - name: print whoami
              run: echo $whoami
            - name: print date
              run: echo $date
            