name: Conditions Tasks
on:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Build Success"
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - if: success()
              run: echo "deploying.."