name: Conditions Tasks
on:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Build Success"
            - run: exit 1
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
              - run: echo "deploying.."