name: Secret Test
on:
    workflow_dispatch:

env:
    DISTRO: ${{secrets.FAVORITE_DISTRO}}

jobs:
    secret:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ secrets.FAVORITE_OS}}"

    env-test:
        needs: secret
        runs-on: ubuntu-latest
        steps:
            - run: echo $DISTRO